version: 0.2
phases:
  install: # Install AWS cli, kubectl (needed for Helm) and Helm
    commands:
       - apt-get update
       - apt install -y awscli git python3
       #- curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
       #- chmod +x ./aws-iam-authenticator
       #- mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
       - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
       - chmod +x kubectl
       - mv ./kubectl /usr/local/bin/kubectl
       #- wget https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
       #- chmod +x ./linux-amd64/helm
       #- mv ./linux-amd64/helm /usr/local/bin/helm
  build:
    commands:
       - "echo nothing to build"
  post_build:
    commands:
       - "echo hello_world"
       - "aws eks update-kubeconfig --name ci-cluster --role-arn arn:aws:iam::745904859815:role/EksCodeBuildkubectlRole"
       - "kubectl get nodes"
       - "kubectl apply -f manifests/selenium-hub.yaml"
  
