apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nginx
    spec:     # pod spec
      containers:
        - name: nginx
          image:  souhmaa/nginx-local:5.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: selenium
  annotations:
    external-dns.alpha.kubernetes.io/hostname: selenium.sb-pld.lefebvre-sarrut.eu
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      name: port0
  selector:
    app: nginx
  type: LoadBalancer
