apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:2.53.1
          ports:
            - containerPort: 4444
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30080
      name: port0
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
