apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-opera
  labels:
    app: selenium-node-opera
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-opera
  template:
    metadata:
      labels:
        app: selenium-node-opera
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-opera
          image: selenium/node-opera:3.141
          ports:
            - containerPort: 5900
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: HUB_HOST
              value: "selenium-hub"
            - name: HUB_PORT
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "1"
            - name: NODE_MAX_SESSION
              value: "1"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
